# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  [push, pull_request]

jobs:

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get -y install libsecp256k1-0
        pip install -r contrib/requirements/requirements-travis.txt
    - name: pytest with tox
      run: |
        tox -e py
    - name: Coveralls
      run: |
        python -m pip install --upgrade pip
        pip install coveralls
        coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push_locale
      if: github.ref == 'refs/heads/master'
      run: |
        pip install requests
        contrib/push_locale

  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Flake8 linter tests
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  Regtest_functional_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:luke-jr/bitcoincore
        sudo apt-get -qq update
        sudo apt-get install -yq bitcoind
        sudo apt-get -y install libsecp256k1-0
        python -m pip install --upgrade pip
        pip install .[tests]
        pip install electrumx
    - name: before_script
      run: |
        electrum/tests/regtest/start_bitcoind.sh
        electrum/tests/regtest/start_electrumx.sh
    - name: script
      run: |
        python -m unittest electrum/tests/regtest.py
